### ISSUE TITLE
Lexing/Parsing errors should explicitly throw exceptions

### ISSUE THREAD

**Issue by twk-rbx** [telus-oss/cel-net#1]
Invalid expressions eg: "1+" or "join('a', 'b'" should throw an exception instead of proceeding with ANTLR's default recovery mechanisms. 

Checking on celParser.NumberOfSyntaxErrors should be sufficient I believe. However it may not catch lexer issues (see https://github.com/antlr/antlr4/issues/3849 for a discussion of parser/lexer defaults in antlr).

This should bring it inline with the behavior of cel-go, otherwise the behavior is determined by  how ANTLR determines to recover from a bad parse - which may be surprising to the user.

**Comment by LamarLugli** [comment]
Changes are included in release v0.1.5.
